# Generated by Django 3.2 on 2023-05-13 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('fabricante', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('ativo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datahora', models.DateTimeField()),
                ('quantidade', models.PositiveIntegerField()),
                ('tipomovimentacao', models.BooleanField()),
                ('local', models.CharField(max_length=255)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicativo.produto')),
            ],
        ),
    ]
