# Generated by Django 3.2 on 2023-05-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='deletado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
