# Generated by Django 3.2 on 2023-05-14 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0003_produto_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
    ]
