# Generated by Django 3.2 on 2023-05-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0005_alter_produto_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
