# Generated by Django 3.2 on 2023-05-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0007_rename_movimentacoes_movimentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='deletado',
            field=models.BooleanField(default=False),
        ),
    ]
